"""
SalinO-Crop — Crop Recommendation Service

STATUS: REAL logic. DEMO data (seeded crop DB from BRRI/BARI sources).

CRITICAL: Crop recommendations are generated by EC tolerance matching, NOT by the LLM.
The LLM only explains the structured recommendation in Bengali.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)


# ─── Reason Codes ─────────────────────────────────────────────────────────────

class ReasonCode:
    HIGH_SALINITY_TOLERANCE = "HIGH_SALINITY_TOLERANCE"
    MODERATE_SALINITY_TOLERANCE = "MODERATE_SALINITY_TOLERANCE"
    SEASON_COMPATIBLE = "SEASON_COMPATIBLE"
    LOW_WATER_REQUIREMENT = "LOW_WATER_REQUIREMENT"
    HALOPHYTE_ALTERNATIVE = "HALOPHYTE_ALTERNATIVE"
    NEAR_EC_LIMIT = "NEAR_EC_LIMIT"
    EXCEEDS_EC_LIMIT = "EXCEEDS_EC_LIMIT"


# ─── Crop Data Structures ─────────────────────────────────────────────────────

@dataclass
class CropVarietyData:
    id: int
    crop_name: str
    crop_name_bn: str
    variety: str
    variety_bn: str
    max_ec_ds_m: float
    tolerance_category: str
    season: str
    water_requirement: str
    notes: str
    notes_bn: str
    source_reference: str
    is_halophyte: bool


@dataclass
class CropRank:
    crop_variety_id: int
    crop_name: str
    crop_name_bn: str
    variety: str
    variety_bn: str
    max_ec_ds_m: float
    tolerance_category: str
    season: str
    score: float           # 0–1
    reason_codes: list[str]
    is_halophyte: bool


@dataclass
class RecommendationResult:
    plot_id: str
    risk_level: str
    predicted_ec_30d: Optional[float]
    predicted_ec_60d: Optional[float]
    predicted_ec_90d: Optional[float]
    season: Optional[str]
    recommended: list[CropRank]
    warning: Optional[str] = None


# ─── Service ──────────────────────────────────────────────────────────────────

class CropRecommendationService:
    """
    Matches predicted EC against crop tolerance thresholds.
    Returns a ranked list of suitable cultivars.

    This is a deterministic algorithm. No ML, no LLM involved.
    """

    def recommend(
        self,
        plot_id: str,
        ec_30d: float,
        ec_60d: float,
        ec_90d: float,
        risk_level: str,
        available_crops: list[CropVarietyData],
        season: Optional[str] = None,
        confidence_30d: float = 1.0,
    ) -> RecommendationResult:
        """
        Rank crops based on tolerance vs predicted EC.

        Scoring logic:
        - Crops with max_ec >= max(ec_30d, ec_60d, ec_90d) are eligible
        - Score = (max_ec - predicted_ec) / max_ec  (margin of safety)
        - Bonus for halophytes (+0.05) and season match (+0.05)
        - Near-limit crops (margin < 10%) get NEAR_EC_LIMIT reason
        """
        peak_ec = max(ec_30d, ec_60d, ec_90d)
        ranked: list[CropRank] = []

        for crop in available_crops:
            if crop.max_ec_ds_m < ec_30d:
                # Below 30-day threshold — not suitable
                continue

            reason_codes = []
            margin = crop.max_ec_ds_m - peak_ec

            # Base score: safety margin as fraction of max tolerance
            score = max(0.0, margin / crop.max_ec_ds_m)

            # Tolerance category bonus
            if crop.tolerance_category in ("tolerant", "highly_tolerant"):
                reason_codes.append(ReasonCode.HIGH_SALINITY_TOLERANCE)
                score += 0.05
            elif crop.tolerance_category == "moderate":
                reason_codes.append(ReasonCode.MODERATE_SALINITY_TOLERANCE)

            # Season match
            if season and (crop.season == season or crop.season == "year_round"):
                reason_codes.append(ReasonCode.SEASON_COMPATIBLE)
                score += 0.05

            # Halophyte bonus
            if crop.is_halophyte:
                reason_codes.append(ReasonCode.HALOPHYTE_ALTERNATIVE)
                score += 0.03

            # Near-limit warning
            if 0 < margin < (crop.max_ec_ds_m * 0.1):
                reason_codes.append(ReasonCode.NEAR_EC_LIMIT)

            ranked.append(CropRank(
                crop_variety_id=crop.id,
                crop_name=crop.crop_name,
                crop_name_bn=crop.crop_name_bn,
                variety=crop.variety,
                variety_bn=crop.variety_bn,
                max_ec_ds_m=crop.max_ec_ds_m,
                tolerance_category=crop.tolerance_category,
                season=crop.season,
                score=round(min(1.0, score), 4),
                reason_codes=reason_codes,
                is_halophyte=crop.is_halophyte,
            ))

        # Sort by score descending
        ranked.sort(key=lambda x: x.score, reverse=True)

        warning = None
        if confidence_30d < 0.6:
            warning = "LOW_CONFIDENCE: Forecast confidence below 60%. Additional ground validation recommended before planting decision."
        if not ranked:
            warning = (warning or "") + " No crops in the database can tolerate this salinity level. Consider remediation."

        return RecommendationResult(
            plot_id=plot_id,
            risk_level=risk_level,
            predicted_ec_30d=round(ec_30d, 3),
            predicted_ec_60d=round(ec_60d, 3),
            predicted_ec_90d=round(ec_90d, 3),
            season=season,
            recommended=ranked[:10],  # Return top 10
            warning=warning,
        )
