"""Init sqlite

Revision ID: e431feb1346d
Revises: 
Create Date: 2026-10-04 19:31:26.440220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e431feb1346d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_varieties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('crop_name_bn', sa.String(length=200), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=False),
    sa.Column('variety_bn', sa.String(length=200), nullable=True),
    sa.Column('max_ec_ds_m', sa.Float(), nullable=False),
    sa.Column('tolerance_category', sa.Enum('SENSITIVE', 'MODERATE', 'TOLERANT', 'HIGHLY_TOLERANT', name='tolerancecategory'), nullable=False),
    sa.Column('season', sa.Enum('AMAN', 'BORO', 'AUS', 'RABI', 'YEAR_ROUND', name='seasontype'), nullable=False),
    sa.Column('water_requirement', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notes_bn', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('is_halophyte', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_bn', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('is_coastal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'ACTIVE', 'DEPRECATED', 'EXPERIMENTAL', name='modelstatus'), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_version', sa.String(length=100), nullable=True),
    sa.Column('feature_version', sa.String(length=100), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_version')
    )
    op.create_table('satellite_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite', sa.String(length=50), nullable=False),
    sa.Column('scene_id', sa.String(length=255), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('district_code', sa.String(length=10), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('raster_path', sa.String(length=1024), nullable=True),
    sa.Column('bands_available', sa.JSON(), nullable=True),
    sa.Column('quality_flag', sa.Enum('GOOD', 'SUSPECT', 'LOW_CONFIDENCE', 'MISSING', name='dataqualityflag'), nullable=False),
    sa.Column('processing_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tide_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=100), nullable=False),
    sa.Column('district_code', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tide_height_m', sa.Float(), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('district_code', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_code', 'observed_at', 'source', name='uq_weather_obs')
    )
    op.create_table('upazilas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_bn', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('full_name_bn', sa.String(length=500), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'EXTENSION_OFFICER', 'DISTRICT_ADMIN', 'SYSTEM_ADMIN', name='userrole'), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('upazila_id', sa.Integer(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('farmer_name', sa.String(length=255), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['upazila_id'], ['upazilas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ground_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=True),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ec_ds_m', sa.Float(), nullable=False),
    sa.Column('soil_depth_cm', sa.Integer(), nullable=True),
    sa.Column('measurement_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('officer_name', sa.String(length=255), nullable=True),
    sa.Column('officer_id_number', sa.String(length=100), nullable=True),
    sa.Column('quality_reviewed', sa.Boolean(), nullable=False),
    sa.Column('approved_for_calibration', sa.Boolean(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salinity_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_ec', sa.Float(), nullable=True),
    sa.Column('rainfall_forecast_mm', sa.Float(), nullable=True),
    sa.Column('tide_height_m', sa.Float(), nullable=True),
    sa.Column('ec_30d', sa.Float(), nullable=True),
    sa.Column('ec_60d', sa.Float(), nullable=True),
    sa.Column('ec_90d', sa.Float(), nullable=True),
    sa.Column('confidence_30d', sa.Float(), nullable=True),
    sa.Column('confidence_60d', sa.Float(), nullable=True),
    sa.Column('confidence_90d', sa.Float(), nullable=True),
    sa.Column('risk_30d', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'UNKNOWN', name='risklevel'), nullable=False),
    sa.Column('risk_60d', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'UNKNOWN', name='risklevel'), nullable=False),
    sa.Column('risk_90d', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'UNKNOWN', name='risklevel'), nullable=False),
    sa.Column('quality_flag', sa.Enum('GOOD', 'SUSPECT', 'LOW_CONFIDENCE', 'MISSING', name='dataqualityflag'), nullable=False),
    sa.Column('model_mode', sa.String(length=50), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salinity_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('satellite_obs_id', sa.UUID(), nullable=True),
    sa.Column('ec_ds_m', sa.Float(), nullable=True),
    sa.Column('ndsi', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'UNKNOWN', name='risklevel'), nullable=False),
    sa.Column('quality_flag', sa.Enum('GOOD', 'SUSPECT', 'LOW_CONFIDENCE', 'MISSING', name='dataqualityflag'), nullable=False),
    sa.Column('spectral_features', sa.JSON(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['satellite_obs_id'], ['satellite_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'UNKNOWN', name='risklevel'), nullable=False),
    sa.Column('predicted_ec_30d', sa.Float(), nullable=True),
    sa.Column('season', sa.Enum('AMAN', 'BORO', 'AUS', 'RABI', 'YEAR_ROUND', name='seasontype'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['salinity_forecasts.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advisory_bn', sa.Text(), nullable=True),
    sa.Column('sms_text_bn', sa.Text(), nullable=True),
    sa.Column('voice_script_bn', sa.Text(), nullable=True),
    sa.Column('officer_summary_en', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('audio_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('structured_facts', sa.JSON(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['salinity_forecasts.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('crop_variety_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['crop_variety_id'], ['crop_varieties.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_items')
    op.drop_table('advisories')
    op.drop_table('recommendations')
    op.drop_table('salinity_predictions')
    op.drop_table('salinity_forecasts')
    op.drop_table('ground_measurements')
    op.drop_table('plots')
    op.drop_table('users')
    op.drop_table('upazilas')
    op.drop_table('weather_observations')
    op.drop_table('tide_observations')
    op.drop_table('satellite_observations')
    op.drop_table('model_versions')
    op.drop_table('districts')
    op.drop_table('crop_varieties')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
